image_size: 256

view:
  checkpoint_path: weights/view.ckpt
  prediction_threshold: 0.5556141668812448
  out_dim: 3
  batch_size: 100

orientation:
  checkpoint_path: weights/orientation.ckpt
  prediction_threshold: 0.5
  out_dim: 2
  batch_size: 100

cardiac_cycle_prediction:
  checkpoint_path: 'weights/cardiac_cycle_prediction.ckpt'

json_generation:
  frames_to_sample: 16
  label: ['LVEF']
  name: 'dataset_name'